services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: bash -c "python manage.py migrate && echo \"from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'pass')\" | ./manage.py shell && python manage.py runserver_plus 0.0.0.0:8000" 
    volumes:
      - ./test_categories:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
