# Generated by Django 3.1.7 on 2021-03-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20210311_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='root'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='product'),
        ),
    ]
